"""Self-contained macOS install/uninstall lifecycle for JL Mixing Automation."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from shlex import quote

from .shell_config import MarkerError, atomic_write, install_block, locate_block, remove_block
from .transactions import create_staging_directory
from .versions import application_root

PUBLIC_COMMANDS = (
    "jl-mixing",
    "new-studio",
    "new-client",
    "new-mix",
    "validate-intake",
    "new-revision",
    "approve-mix",
    "create-delivery",
)

MANAGED_LAUNCHER = "JL Mixing Automation managed launcher"
MANAGED_INTEGRATION = "JL Mixing Automation managed shell integration"


def _fail(message: str, code: int = 1) -> int:
    print(f"Error: {message}", file=sys.stderr)
    return code


def _default_prefix() -> Path:
    override = os.environ.get("JL_MIXING_INSTALL_PREFIX")
    if override:
        return Path(override).expanduser().absolute()
    return (Path.home() / ".local").absolute()


def _is_managed(path: Path, marker: str) -> bool:
    if not path.is_file() or path.is_symlink():
        return False
    try:
        return marker in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def _shell_target() -> tuple[str, Path] | None:
    configured = os.environ.get("SHELL", "")
    name = Path(configured).name
    if name == "zsh":
        return name, Path.home() / ".zshrc"
    if name == "bash":
        return name, Path.home() / ".bashrc"
    return None


def _managed_shell_block(bin_dir: Path) -> bytes:
    text = (
        "# >>> JL Mixing managed configuration >>>\n"
        f"export PATH={quote(str(bin_dir))}:\"$PATH\"\n\n"
        "if command -v jl-mixing-shell-integration >/dev/null 2>&1; then\n"
        "    source \"$(command -v jl-mixing-shell-integration)\"\n"
        "fi\n"
        "# <<< JL Mixing managed configuration <<<\n"
    )
    return text.encode("utf-8")


def _copy_application(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=False)
    for name in ("VERSION", "API_VERSION", "LICENSE", "README.md", "CHANGELOG.md"):
        src = source / name
        if not src.is_file():
            raise RuntimeError(f"installation package is missing {name}")
        shutil.copy2(src, destination / name)

    required_dirs = ("bin", "src", "api", "schemas", "templates", "docs", "runtime", "macos")
    optional_dirs = ("lib", "tools", "packaging")
    for name in required_dirs:
        src = source / name
        if not src.is_dir():
            raise RuntimeError(f"installation package is missing {name}")
        shutil.copytree(src, destination / name, symlinks=True)
    for name in optional_dirs:
        src = source / name
        if src.is_dir():
            shutil.copytree(src, destination / name, symlinks=True)

    runtime = destination / "runtime" / "python"
    if not runtime.is_file():
        raise RuntimeError("installation package is missing runtime/python")
    runtime.chmod(runtime.stat().st_mode | 0o111)
    for path in (destination / "bin").iterdir():
        if path.is_file():
            path.chmod(path.stat().st_mode | 0o111)
    for name in ("install.sh", "uninstall.sh"):
        path = destination / "macos" / name
        if path.is_file():
            path.chmod(path.stat().st_mode | 0o111)


def _write_launchers(stage_bin: Path, app_dir: Path, prefix: Path, source: Path) -> None:
    stage_bin.mkdir(parents=True, exist_ok=True)
    for command in PUBLIC_COMMANDS:
        launcher = stage_bin / command
        launcher.write_text(
            "#!/usr/bin/env bash\n"
            f"# {MANAGED_LAUNCHER}. Generated by macos/install.sh.\n"
            f"export JL_MIXING_HOME={quote(str(app_dir))}\n"
            f"export JL_MIXING_PYTHON={quote(str(app_dir / 'runtime' / 'python'))}\n"
            f"exec {quote(str(app_dir / 'bin' / command))} \"$@\"\n",
            encoding="utf-8",
        )
        launcher.chmod(0o755)

    integration_source = source / "bin" / "jl-mixing-shell-integration"
    integration = stage_bin / "jl-mixing-shell-integration"
    shutil.copy2(integration_source, integration)
    integration.chmod(0o755)

    uninstall = stage_bin / "jl-mixing-uninstall"
    uninstall.write_text(
        "#!/usr/bin/env bash\n"
        f"# {MANAGED_LAUNCHER}. Generated by macos/install.sh.\n"
        f"exec {quote(str(app_dir / 'macos' / 'uninstall.sh'))} --prefix {quote(str(prefix))} \"$@\"\n",
        encoding="utf-8",
    )
    uninstall.chmod(0o755)


def _maybe_fail(point: str) -> None:
    if os.environ.get("JL_MIXING_TEST_FAIL_INSTALL_AT") == point:
        raise RuntimeError(f"injected installation failure at {point}")


def _read_state(app_dir: Path) -> dict[str, object]:
    path = app_dir / "install-state.json"
    if not path.is_file():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def install(prefix: Path, *, shell_integration_requested: bool) -> int:
    source = application_root()
    prefix = prefix.expanduser().absolute()
    app_dir = prefix / "share" / "jl-mixing"
    bin_dir = prefix / "bin"
    state_before = _read_state(app_dir)

    runtime = source / "runtime" / "python"
    if not runtime.is_file():
        return _fail("installation package does not contain runtime/python.", 3)

    for command in PUBLIC_COMMANDS:
        destination = bin_dir / command
        if destination.exists() and not _is_managed(destination, MANAGED_LAUNCHER):
            return _fail(f"refusing to overwrite unmanaged command: {destination}", 5)
    for name, marker in (
        ("jl-mixing-shell-integration", MANAGED_INTEGRATION),
        ("jl-mixing-uninstall", MANAGED_LAUNCHER),
    ):
        destination = bin_dir / name
        if destination.exists() and not _is_managed(destination, marker):
            return _fail(f"refusing to overwrite unmanaged command: {destination}", 5)

    shell_name = ""
    startup_file: Path | None = None
    shell_enabled = False
    startup_created = False
    startup_original: bytes | None = None
    staged_startup: bytes | None = None

    if shell_integration_requested:
        target = _shell_target()
        if target is not None:
            shell_name, startup_file = target
            shell_enabled = True
    elif state_before:
        shell_state = state_before.get("shell_integration")
        if isinstance(shell_state, dict) and shell_state.get("enabled") is True:
            stored = shell_state.get("startup_file")
            stored_shell = shell_state.get("shell")
            if isinstance(stored, str) and stored:
                startup_file = Path(stored)
                shell_name = stored_shell if isinstance(stored_shell, str) else ""
                shell_enabled = True

    try:
        if startup_file is not None:
            startup_original = startup_file.read_bytes() if startup_file.exists() else b""
            startup_created = not startup_file.exists()
            if shell_integration_requested:
                staged_startup = install_block(startup_original, _managed_shell_block(bin_dir))
            else:
                locate_block(startup_original)
    except (OSError, MarkerError) as exc:
        return _fail(f"unsafe shell configuration: {exc}", 5)

    prefix.mkdir(parents=True, exist_ok=True)
    bin_dir.mkdir(parents=True, exist_ok=True)
    stage_root = create_staging_directory(prefix, ".jl-mixing-install-stage-")
    backup_root = create_staging_directory(prefix, ".jl-mixing-install-backup-")
    stage_app = stage_root / "share" / "jl-mixing"
    stage_bin = stage_root / "bin"
    commit_started = False

    managed_names = (*PUBLIC_COMMANDS, "jl-mixing-shell-integration", "jl-mixing-uninstall")
    try:
        _copy_application(source, stage_app)
        _write_launchers(stage_bin, app_dir, prefix, source)
        shell_state = {
            "enabled": shell_enabled,
            "shell": shell_name,
            "startup_file": str(startup_file) if startup_file is not None else "",
            "startup_file_created": startup_created,
            "startup_file_added_separator": False,
        }
        (stage_app / "install-state.json").write_text(
            json.dumps({"installation_prefix": str(prefix), "shell_integration": shell_state}, indent=2) + "\n",
            encoding="utf-8",
        )

        if not (stage_app / "runtime" / "python").is_file():
            raise RuntimeError("staged runtime verification failed")
        for name in managed_names:
            if not (stage_bin / name).is_file():
                raise RuntimeError(f"staged launcher missing: {name}")

        (backup_root / "bin").mkdir(parents=True, exist_ok=True)
        if app_dir.is_dir():
            shutil.move(str(app_dir), str(backup_root / "app"))
        for name in managed_names:
            existing = bin_dir / name
            if existing.is_file():
                shutil.copy2(existing, backup_root / "bin" / name)
        if startup_file is not None and startup_file.exists():
            (backup_root / "startup-file").write_bytes(startup_file.read_bytes())
        commit_started = True

        app_dir.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(stage_app), str(app_dir))
        _maybe_fail("after-application")

        for name in managed_names:
            temporary = bin_dir / f".{name}.jl-mixing-{os.getpid()}"
            shutil.copy2(stage_bin / name, temporary)
            os.replace(temporary, bin_dir / name)
        _maybe_fail("after-launchers")

        if startup_file is not None and staged_startup is not None:
            atomic_write(startup_file, staged_startup)
        _maybe_fail("after-shell")

        if not (app_dir / "runtime" / "python").is_file():
            raise RuntimeError("installed runtime verification failed")
        for name in managed_names:
            if not (bin_dir / name).is_file():
                raise RuntimeError(f"installed launcher missing: {name}")

        shutil.rmtree(backup_root, ignore_errors=True)
        commit_started = False
    except Exception as exc:
        if commit_started:
            shutil.rmtree(app_dir, ignore_errors=True)
            backup_app = backup_root / "app"
            if backup_app.is_dir():
                app_dir.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(backup_app), str(app_dir))
            for name in managed_names:
                destination = bin_dir / name
                try:
                    destination.unlink()
                except FileNotFoundError:
                    pass
                backup = backup_root / "bin" / name
                if backup.is_file():
                    shutil.copy2(backup, destination)
            if startup_file is not None:
                backup_startup = backup_root / "startup-file"
                if backup_startup.is_file():
                    atomic_write(startup_file, backup_startup.read_bytes())
                elif startup_created:
                    try:
                        startup_file.unlink()
                    except FileNotFoundError:
                        pass
        print("Installation failed; previous installation restored.", file=sys.stderr)
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    finally:
        shutil.rmtree(stage_root, ignore_errors=True)
        if not commit_started:
            shutil.rmtree(backup_root, ignore_errors=True)

    version = (app_dir / "VERSION").read_text(encoding="utf-8").strip()
    print(f"Installed JL Mixing Automation {version}")
    print(f"Application: {app_dir}")
    print(f"Commands:    {bin_dir}")
    if shell_integration_requested and startup_file is not None:
        print(f"Shell setup: {startup_file}")
        print("Open a new Terminal window or tab to activate JL Mixing.")
    elif not shell_integration_requested:
        print("Shell setup: not modified (--no-shell-integration)")
    else:
        print("Shell setup: unsupported configured shell; no startup file was modified.")
    print("\nNext: new-studio")
    return 0


def uninstall(prefix: Path) -> int:
    prefix = prefix.expanduser().absolute()
    app_dir = prefix / "share" / "jl-mixing"
    bin_dir = prefix / "bin"
    state = _read_state(app_dir)

    shell_state = state.get("shell_integration") if isinstance(state, dict) else None
    startup_file: Path | None = None
    startup_created = False
    if isinstance(shell_state, dict) and shell_state.get("enabled") is True:
        value = shell_state.get("startup_file")
        if isinstance(value, str) and value:
            startup_file = Path(value)
        startup_created = shell_state.get("startup_file_created") is True

    for name in (*PUBLIC_COMMANDS, "jl-mixing-uninstall"):
        path = bin_dir / name
        if path.exists() and not _is_managed(path, MANAGED_LAUNCHER):
            return _fail(f"refusing to remove unmanaged command: {path}", 5)
    integration = bin_dir / "jl-mixing-shell-integration"
    if integration.exists() and not _is_managed(integration, MANAGED_INTEGRATION):
        return _fail(f"refusing to remove unmanaged shell integration: {integration}", 5)

    try:
        if startup_file is not None and startup_file.exists():
            original = startup_file.read_bytes()
            updated = remove_block(original, require_present=False)
            if startup_created and not updated:
                startup_file.unlink()
            elif updated != original:
                atomic_write(startup_file, updated)
    except (OSError, MarkerError) as exc:
        return _fail(f"unable to remove managed shell configuration: {exc}", 5)

    for name in (*PUBLIC_COMMANDS, "jl-mixing-shell-integration", "jl-mixing-uninstall"):
        path = bin_dir / name
        try:
            path.unlink()
        except FileNotFoundError:
            pass
    shutil.rmtree(app_dir, ignore_errors=True)

    print("Uninstalled JL Mixing Automation.")
    print("Studio workspaces and project data were not modified.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="jl-mixing-macos-installer")
    sub = parser.add_subparsers(dest="command", required=True)

    install_parser = sub.add_parser("install")
    install_parser.add_argument("--prefix")
    install_parser.add_argument("--no-shell-integration", action="store_true")

    uninstall_parser = sub.add_parser("uninstall")
    uninstall_parser.add_argument("--prefix")

    args = parser.parse_args()
    prefix = Path(args.prefix).expanduser() if args.prefix else _default_prefix()
    if args.command == "install":
        return install(prefix, shell_integration_requested=not args.no_shell_integration)
    return uninstall(prefix)


if __name__ == "__main__":
    raise SystemExit(main())
