#!/usr/bin/env bash
# Verify managed shell configuration, opt-out behavior, conflicts, and fallback uninstall.
set -eu

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
. "$ROOT/tests/test-helper.sh"

require_test_command python3
require_test_command jq
python3 -c 'import jsonschema' >/dev/null 2>&1 || {
    if [ "${JL_TEST_STRICT:-0}" = "1" ]; then
        fail "Shell installation tests require jsonschema."
    fi
    echo "[SKIP] Shell installation tests require jsonschema."
    exit 0
}

temp_root="$(new_test_dir)"
trap 'rm -rf "$temp_root"' EXIT HUP INT TERM

# --no-shell-integration installs the one bin path and integration file without
# changing the user's startup file. It also removes a managed v1.0 launcher.
opt_home="$temp_root/opt-home"
opt_prefix="$temp_root/opt-prefix"
mkdir -p "$opt_home" "$opt_prefix/bin"
printf 'export KEEP_ZSH=1\n' > "$opt_home/.zshrc"
cat > "$opt_prefix/bin/complete-project" <<'LEGACY'
#!/usr/bin/env bash
# JL Mixing Automation managed launcher. Generated by install.sh.
LEGACY
chmod +x "$opt_prefix/bin/complete-project"
HOME="$opt_home" SHELL=/bin/zsh JL_MIXING_TEST_SYSTEM_SITE_PACKAGES=1 \
    "$ROOT/install.sh" --prefix "$opt_prefix" --no-shell-integration >/dev/null
assert_eq "export KEEP_ZSH=1" "$(cat "$opt_home/.zshrc")" \
    "opt-out preserves shell startup bytes"
assert_file_exists "$opt_prefix/bin/jl-mixing-shell-integration"
assert_path_not_exists "$opt_prefix/bin/complete-project"
assert_eq "false" "$(jq -r '.shell_integration.enabled' \
    "$opt_prefix/share/jl-mixing/install-state.json")" \
    "opt-out install state disables shell cleanup"
HOME="$opt_home" SHELL=/bin/zsh "$opt_prefix/bin/jl-mixing-uninstall" >/dev/null
assert_eq "export KEEP_ZSH=1" "$(cat "$opt_home/.zshrc")" \
    "opt-out uninstall preserves shell startup bytes"

# A startup file created solely for the managed block is removed when uninstall
# leaves it empty.
created_home="$temp_root/created-home"
created_prefix="$temp_root/created-prefix"
mkdir -p "$created_home"
HOME="$created_home" SHELL=/bin/bash JL_MIXING_TEST_SYSTEM_SITE_PACKAGES=1 \
    "$ROOT/install.sh" --prefix "$created_prefix" >/dev/null
assert_file_exists "$created_home/.bashrc"
assert_json_eq "true" "$created_prefix/share/jl-mixing/install-state.json" \
    '.shell_integration.startup_file_created' "install records created startup file"
HOME="$created_home" SHELL=/bin/bash "$created_prefix/bin/jl-mixing-uninstall" >/dev/null
assert_path_not_exists "$created_home/.bashrc"

# Malformed markers fail before any application or launcher is committed.
bad_home="$temp_root/bad-home"
bad_prefix="$temp_root/bad-prefix"
mkdir -p "$bad_home"
printf '# >>> JL Mixing managed configuration >>>\n' > "$bad_home/.bashrc"
assert_failure "malformed shell markers block installation" env \
    HOME="$bad_home" SHELL=/bin/bash JL_MIXING_TEST_SYSTEM_SITE_PACKAGES=1 \
    "$ROOT/install.sh" --prefix "$bad_prefix"
assert_path_not_exists "$bad_prefix/share/jl-mixing"

# Unmanaged command collisions are never overwritten.
conflict_home="$temp_root/conflict-home"
conflict_prefix="$temp_root/conflict-prefix"
mkdir -p "$conflict_home" "$conflict_prefix/bin"
printf '# user command\n' > "$conflict_prefix/bin/new-studio"
assert_failure "unmanaged launcher conflict blocks installation" env \
    HOME="$conflict_home" SHELL=/bin/bash JL_MIXING_TEST_SYSTEM_SITE_PACKAGES=1 \
    "$ROOT/install.sh" --prefix "$conflict_prefix" --no-shell-integration
assert_eq "# user command" "$(cat "$conflict_prefix/bin/new-studio")" \
    "unmanaged launcher remains unchanged"


echo "[OK] shell installation lifecycle ($TEST_COUNT assertions)"
